# Luke Riechert
## Week 11 11/05/2020
### Python NumPy Universal Functions

In [1]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z = []

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [2]:
#zip

fname = ('Alice', 'Bob', 'Christy')
lname = ('Charlie', 'Clark', 'Robert')

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [4]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [5]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
arr1 = np.random.randn(10)
arr1

array([-0.50309074, -1.81991785, -0.13524979, -0.08124283, -0.89256558,
       -1.05362299, -0.88474724, -0.55683795, -0.38223504, -0.49838857])

In [10]:
arr2=np.random.randn(10)

arr2

array([-0.20470046,  0.05976165, -0.71339716,  0.99705768, -0.61088815,
        0.20064488, -0.98331111, -0.83545334,  0.44663153, -1.15514496])

In [11]:
np.add(arr1,arr2)

array([-0.70779119, -1.7601562 , -0.84864695,  0.91581485, -1.50345373,
       -0.85297812, -1.86805835, -1.39229129,  0.06439649, -1.65353353])

In [12]:
np.maximum(arr1,arr2)

array([-0.20470046,  0.05976165, -0.13524979,  0.99705768, -0.61088815,
        0.20064488, -0.88474724, -0.55683795,  0.44663153, -0.49838857])

In [13]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [15]:
np.where(arr < 4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [17]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [21]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [23]:
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20,  3,  4, 50])